---
platforms:
  - name: remote
    host: 51.250.105.54
    user: matcai
    ssh_extra_args: "-o StrictHostKeyChecking=no"
    private_key_file: ~/.ssh/ssh_molecule_test  
    # become: true
    ansible_connection: ssh  

provisioner:
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          remote:
            ansible_host: 51.250.105.54
            ansible_user: matcai
            ansible_private_key_file: ~/.ssh/ssh_molecule_test
            # ansible_become: true

verifier:
  name: ansible
  
scenario:
  name: default
  ## below test sequence starts with `destroy` to ensure we have clean infrastructure state.
  test_sequence:
    - destroy
    - create
    - converge
    - verify
    - destroy