---
- name: Setup and run Django application
  hosts: app
  become: true
  vars:
    app_path: /opt/django-locallibrary-tutorial
  
  tasks:
  - name: Ansible Simple Variable Example Usage
    debug:
      msg: "!!!{{ app_path }}!!!"

  tasks:
    - name: Ensure Python 3 and pip are installed
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - python3-venv

    - name: Install required python packages
      pip:
        requirements: "{{ app_path }}/requirements.txt"
        virtualenv: "{{ app_path }}/venv"
        virtualenv_command: python3 -m venv

    - name: Make Django migrations
      command: "{{ app_path }}/venv/bin/python {{ app_path }}/manage.py makemigrations"
      args:
        chdir: "{{ app_path }}"

    - name: Apply Django migrations
      command: "{{ app_path }}/venv/bin/python {{ app_path }}/manage.py migrate"
      args:
        chdir: "{{ app_path }}"

    - name: Collect static files
      command: "{{ app_path }}/venv/bin/python {{ app_path }}/manage.py collectstatic --noinput"
      args:
        chdir: "{{ app_path }}"

    - name: Run Django tests
      command: "{{ app_path }}/venv/bin/python {{ app_path }}/manage.py test"

    - name: Create Django superuser
      command: "{{ app_path }}/venv/bin/python {{ app_path }}/manage.py createsuperuser"
      args:
        chdir: "{{ app_path }}"
      ignore_errors: true

    - name: Start the Django application
      command: "{{ app_path }}/venv/bin/python {{ app_path }}/manage.py runserver"
      args:
        chdir: "{{ app_path }}"
