---
- hosts: all
  tasks:
    # - name: Install OpenVPN deps
    #   apt:
    #     name: "{{ item }}"
    #     state: present
    #   loop:
    #     - openvpn
    #     - easy-rsa
    # # - name: "Remove CA directory"
    # #   file:
    # #     state: absent
    # #     path: "~/openvpn-ca/"
    # - name: "Setting up CA"
    #   command: make-cadir ~/openvpn-ca
    #   args:
    #     creates: ~/openvpn-ca
    # # - name: echo
    # #   command: echo ~
    # #   register: echo
    # # - debug: msg="{{ echo.stdout }}"
    # - name: "Setting openssl config file path"
    #   lineinfile: 
    #     path: ~/openvpn-ca/vars
    #     regexp: 'KEY_CONFIG' 
    #     line: 'export KEY_CONFIG="$HOME/openvpn-ca/openssl-easyrsa.cnf"'

    # - name: "Setting the CA properties country"
    #   lineinfile: 
    #     path: ~/openvpn-ca/vars
    #     regexp: 'KEY_COUNTRY' 
    #     line: 'export KEY_COUNTRY="US"'

    # - name: "Setting the CA properties province"
    #   lineinfile: 
    #     path: ~/openvpn-ca/vars
    #     regexp: 'KEY_PROVINCE' 
    #     line: 'export KEY_PROVINCE="SPB"'

    # - name: "Setting the CA properties city"
    #   lineinfile: 
    #     path: ~/openvpn-ca/vars
    #     regexp: 'KEY_CITY' 
    #     line: 'export KEY_CITY="SPB"'

    # - name: "Setting the CA properties organization"
    #   lineinfile: 
    #     path: ~/openvpn-ca/vars
    #     regexp: 'KEY_ORG' 
    #     line: 'export KEY_ORG="none"'

    # - name: "Setting the CA properties email"
    #   lineinfile: 
    #     path: ~/openvpn-ca/vars
    #     regexp: 'KEY_EMAIL' 
    #     line: 'export KEY_EMAIL="maxim20031128@gmail.com"'     

    # - name: "Setting the CA properties OU"
    #   lineinfile: 
    #     path: ~/openvpn-ca/vars
    #     regexp: 'KEY_OU' 
    #     line: 'export KEY_OU="Community"'     

    # - name: "Setting the CA properties name"
    #   lineinfile: 
    #     path: ~/openvpn-ca/vars
    #     regexp: 'KEY_NAME' 
    #     line: 'export KEY_NAME="server"'    

    - name: "Start clean"
      shell: >
          yes "yes" | ~/openvpn-ca/easyrsa clean-all;
          
    # - name: "Start clean"
    # shell: ~/openvpn-ca/clean-all
    - name: "Build root CA certificate"
      shell:  yes "yes" | ./easyrsa init-pki && yes "1111" | ./easyrsa build-ca
      args:
        chdir: ~/openvpn-ca

    - name: "Build server certificate"
      # shell: yes "1111" | ./easyrsa build-server-full server 
      # args:
      #   chdir: ~/openvpn-ca



      expect:
        command: ./easyrsa build-server-full server 
        responses:
          "PEM pass phrase": '1111'
          "request details": 'yes'
          "private/ca.key": '1111'
      args:
        chdir: ~/openvpn-ca


# - name: "Build root CA certificate"
#   shell: source ~/openvpn-ca/vars && ~/openvpn-ca/clean-all && ~/openvpn-ca/pkitool --initca
#   args:
#     chdir: ~/openvpn-ca
#     executable: /bin/bash
#   tags:
#     - buildca
# shell: >
#     ~/openvpn-ca/easyrsa clean-all;
#     yes "" | ~/openvpn-ca/easyrsa build-ca;
