---
- hosts: all
  tasks:
    - name: Install OpenVPN deps
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - openvpn
        - easy-rsa
    # - name: "Remove CA directory"
    #   file:
    #     state: absent
    #     path: "~/openvpn-ca/"
    - name: "Setting up CA"
      command: make-cadir ~/openvpn-ca
      args:
        creates: ~/openvpn-ca
    - name: "Setting openssl config file path"
      lineinfile: 
        path: ~/openvpn-ca/vars
        regexp: 'KEY_CONFIG' 
        line: 'export KEY_CONFIG="~/openvpn-ca/openssl-easyrsa.cnf"'

    - name: "Setting the CA properties country"
      lineinfile: 
        path: ~/openvpn-ca/vars
        regexp: 'KEY_COUNTRY' 
        line: 'export KEY_COUNTRY="{{ openvpn_key_country }}"'

    - name: "Setting the CA properties province"
      lineinfile: 
        path: ~/openvpn-ca/vars
        regexp: 'KEY_PROVINCE' 
        line: 'export KEY_PROVINCE="{{ openvpn_key_province }}"'

    - name: "Setting the CA properties city"
      lineinfile: 
        path: ~/openvpn-ca/vars
        regexp: 'KEY_CITY' 
        line: 'export KEY_CITY="{{ openvpn_key_city }}"'

    - name: "Setting the CA properties organization"
      lineinfile: 
        path: ~/openvpn-ca/vars
        regexp: 'KEY_ORG' 
        line: 'export KEY_ORG="{{ openvpn_key_org }}"'

    - name: "Setting the CA properties email"
      lineinfile: 
        path: ~/openvpn-ca/vars
        regexp: 'KEY_EMAIL' 
        line: 'export KEY_EMAIL="{{ openvpn_key_email }}"'     

    - name: "Setting the CA properties OU"
      lineinfile: 
        path: ~/openvpn-ca/vars
        regexp: 'KEY_OU' 
        line: 'export KEY_OU="Community"'     

    - name: "Setting the CA properties name"
      lineinfile: 
        path: ~/openvpn-ca/vars
        regexp: 'KEY_NAME' 
        line: 'export KEY_NAME="server"'    

    # - name: "Start clean"
    #   shell: >
    #       yes "yes" | ~/openvpn-ca/easyrsa clean-all;
          
    # # - name: "Start clean"
    # # shell: ~/openvpn-ca/clean-all

    # - name: "Build root CA certificate"
    #   shell:  yes "yes" | ./easyrsa init-pki && yes "1111" | ./easyrsa build-ca
    #   args:
    #     chdir: ~/openvpn-ca

    # - name: "Build CRL"

    #   shell: yes "1111" | ./easyrsa gen-crl
    #   args:
    #     chdir: ~/openvpn-ca

    # - name: "Build server certificate"

    #   expect:
    #     command: ./easyrsa build-server-full server 
    #     responses:
    #       "PEM pass phrase": '1111'
    #       "request details": 'yes'
    #       "private/ca.key": '1111'
    #   args:
    #     chdir: ~/openvpn-ca

    # - name: OpenVPN | PKI | Build ta.key
    #   shell: openvpn --genkey --secret ta.key
    #   args:
    #     chdir: ~/openvpn-ca/pki

    # - name: "Build DH"
    #   expect:
    #     command: ./easyrsa gen-dh
    #     responses:
    #       "Overwrite": 'yes'
    #   args:
    #     chdir: ~/openvpn-ca

    # - name: OpenVPN | Add Clients | Get CA cert
    #   fetch:
    #     src: ~/openvpn-ca/pki/ca.crt
    #     dest: "{{ playbook_dir }}/../fetched_creds/test/ca.crt"
    #     flat: yes


      